### ISSUE TITLE
Got one crash

### ISSUE THREAD

**Issue by anaseto** [nhartland/golflike#3]
Hi,

I played a couple of games, and then got a crash, just when the ball was going to the hole. I played a couple games after, and it did not happen again, so not sure was was going on, it seems to has something to do with competition stuff (unless it's something strange with my lua installation, I'm on OpenBSD). I installed using luarocks.

```
Caught an error:
...anaseto/.luarocks/share/lua/5.3/golflike/competition.lua:85: invalid order function for sorting
stack traceback:
        [C]: in function 'table.sort'
        ...anaseto/.luarocks/share/lua/5.3/golflike/competition.lua:85: in function 'golflike.competition.rank'
        ...anaseto/.luarocks/share/lua/5.3/golflike/competition.lua:121: in function 'golflike.competition.get_standings_message'
        .../anaseto/.luarocks/share/lua/5.3/golflike/score_hole.lua:28: in function 'golflike.score_hole.control'
        ...rocks/lib/luarocks/rocks-5.3/golflike/scm-1/bin/golflike:51: in field 'update'
        ...rocks/lib/luarocks/rocks-5.3/golflike/scm-1/bin/golflike:81: in function <...rocks/lib/luarocks/rocks-5.3/golflike/scm-1/bin/golflike:80>
        [C]: in function 'xpcall'
        ...rocks/lib/luarocks/rocks-5.3/golflike/scm-1/bin/golflike:93: in main chunk
        [C]: in ?
```

**Comment by nhartland** [comment]
Thanks for the bug report!

It's an interesting one, did this happen on the first/last hole in a course?
I can't see anything directly wrong with the sort function, so presumably it's getting badly-formed input at some point. I've put a couple of asserts in to see if I can catch the problem.

**Comment by anaseto** [comment]
> It's an interesting one, did this happen on the first/last hole in a course?

I think it was the second or third, but it does not seem to be the reason, because I played again and I had a crash in the 5th hole. Hm, maybe it happens if you play really bad? Haha, I think I managed to win only in one or two of the maps, and then got a +7 or something like that after playing really really bad.

**Comment by anaseto** [comment]
So, I was intrigued and did a little search. It seems that a correct sorting function f(a,b) in lua should be such that if f(a,b) then not f(a,b). Could it be related to that ? In other words, it could happen if `suma == sumb` and neither `a.name` nor `b.name` are equal to `PLAYER` (or both).

**Comment by nhartland** [comment]
I thought about that but then the default sort function is a strict '<' which would also provide f(a,b) == f(b,a). But that I guess is a Lua built-in rather than actual Lua script so maybe that is handled differently. Let's try, I'll make that case explicit.

**Comment by anaseto** [comment]
Maybe I'm missing something, but it seems to me that if the function happens to compare two non-players with the same score, then the order function is not strict (both f(a,b) and f(b,a) return false in such a case, which cannot happen in a strict order), so a possible solve could be to return `string.len(a.name) < string.len(b.name)` in case of equality, which works if all names are different.

**Comment by nhartland** [comment]
Right, I just pushed a change which does that, making the order function always return true for one of the (a,b) (b,a) permutations. I just added an 'id' tag to each player and sort by that in case of a score tie. The player having an id of '-1' meaning that they are always favoured in the tie-break.

Hopefully this should do the trick!

**Comment by anaseto** [comment]
I completed a full course with 9 holes without problems, in spite of a couple of players having the same score, so I think it's fixed indeed!

Fun game, BTW. Maybe there should be some moving obstacles, like some birds or something :) Though, I should probably not say that, because I'm still bad enough at the game, haha.

**Comment by nhartland** [comment]
Excellent, thanks for the help! Yeah, I was also thinking moving obstacles are an option, add a bit of dynamism to the map.
